### ISSUE TITLE
Error while running script

### ISSUE THREAD

**Issue by enricostano** [CollectivaT-dev/TimeOverflow#4]
```
$ docker-compose up
Creating volume "timeoverflow_to_data_results" with default driver
Creating timeoverflow_to_data_1 ... 
Creating timeoverflow_to_data_1 ... done
Attaching to timeoverflow_to_data_1
to_data_1  | Number of arguments:  2  arguments.
to_data_1  | Argument List:  ['script_bank_profiling.py', '2020-01-01']
to_data_1  | Start date:  2013-01-01
to_data_1  | End date:  2020-01-01
to_data_1  | Date used to define active members: 2019-10-01 00:00:00
to_data_1  | Number of transfers:  (0, 10)
to_data_1  | after removing old accounts:  (0, 14)
to_data_1  | after removing transfers with no bank associated:  (0, 11)
to_data_1  | Traceback (most recent call last):
to_data_1  |   File "script_bank_profiling.py", line 623, in <module>
to_data_1  |     main(psql_config, viz_db_config)
to_data_1  |   File "script_bank_profiling.py", line 425, in main
to_data_1  |     d1.columns=column_names
to_data_1  |   File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 5287, in __setattr__
to_data_1  |     return object.__setattr__(self, name, value)
to_data_1  |   File "pandas/_libs/properties.pyx", line 67, in pandas._libs.properties.AxisProperty.__set__
to_data_1  |   File "/usr/local/lib/python3.6/site-packages/pandas/core/generic.py", line 661, in _set_axis
to_data_1  |     self._data.set_axis(axis, labels)
to_data_1  |   File "/usr/local/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 178, in set_axis
to_data_1  |     f"Length mismatch: Expected axis has {old_len} elements, new "
to_data_1  | ValueError: Length mismatch: Expected axis has 1 elements, new values have 11 elements
timeoverflow_to_data_1 exited with code 1
```

**Comment by enricostano** [comment]
Fixed by https://github.com/CollectivaT-dev/TimeOverflow/commit/98c0d1339f3eae1dc6acb6c97e849fd696ee6242
